<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
    
            array(
                'nombre' => "TYR CXT-1 TRAINER",
                'precio' => 153.99,
                'imagen' => "tyr-cxt",
                'categoria_id' => 1,
                'disponible' => true,
                'descripcion' => "Las TYR CXT-1 Trainer revolucionaron el deporte cuando se dieron a conocer en los Crossfit Games 2022.Entresuela de espuma de NRG con una excelente capacidad de respuesta - Paredes laterales de goma que se extienden alrededor del talón para una mayor estabilidad y tracción - Lengüeta en el talón duradera para un deslizamiento suave durante los HSPU",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "UNDER ARMOUR TRIBASE REIGN 5",
                'precio' => 130.0,
                'imagen' => "reign5",
                'categoria_id' => 1,
                'disponible' => true,
                'descripcion' => "Las Tribase Reign 5 son la quinta edición de las emblemáticas zapatillas de cross training de Under Armour y sus mejoras ejemplifican a la perfección la inversión que hace la marca alemana en tecnología e investigación para poder brindar a los atletas el mejor equipamiento. - Nueva tecnología UA Warp en el upper - Nuevo sistema de cordones que se ajusta a la anatomía natural del pie.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "NIKE METCON 9",
                'precio' => 139.99,
                'imagen' => "metcon9",
                'categoria_id' => 1,
                'disponible' => true,
                'descripcion' => "Las zapatillas de CrossFit Nike Metcon 9 presentan un diseño totalmente nuevo para posicionarse como la mejor Metcon hasta la fecha. Los 3 factores más importantes que se han tenido en cuenta durante su diseño son: la estabilidad, la durabilidad y la sostenibilidad - El Hyperlift (la placa de TPU del tacón) es más grande en esta última edición para proporcionar una mayor estabilidad - El Rope Wrap (paredes laterales de goma) es mucho más alto que en su anterior versión para ser extremadamente durable y proteger aún más la zapatilla de la abrasión de la cuerda.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "REEBOK LEGACY LIFTER III",
                'precio' => 199.99,
                'imagen' => "legacy-lifter3",
                'categoria_id' => 1,
                'disponible' => true,
                'descripcion' => "Las zapatillas de halterofilia son indispensables para cualquier atleta que entrena levantamiento de pesas. Las Reebok Legacy Lifter III pretenden maximizar la sujeción y la estabilidad permitiendo el ajuste perfecto a través de la nueva lengüeta con la tecnología PUMP. - Entresuela de espuma EVA para un equilibrio perfecto entre soporte y reactividad en la puntera. -  Clip de TPU en el talónpara asegurar estabilidad",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "PANTALON CORTO NIKE DRI-FIT KNIT 6.0 AOP",
                'precio' => 27.97,
                'imagen' => "pantalon-dryfit",
                'categoria_id' => 2,
                'disponible' => true,
                'descripcion' => "Pantalón corto ideal para Cross Training, en verde y multicolor, para hombre.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "SHORT UNDER ARMOUR PEAK WOVEN",
                'precio' => 65.0,
                'imagen' => "peak-woven",
                'categoria_id' => 2,
                'disponible' => true,
                'descripcion' => "Short blanco crudo, ideal para Fitness & Gym y Activity. Para hombre.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "PANTALON CORTO ADIDAS CLUB",
                'precio' => 40.0,
                'imagen' => "adidas-club",
                'categoria_id' => 2,
                'disponible' => true,
                'descripcion' => "Pantalón corto gris, perfecto para Fitness & Gym y Activity. Para hombre.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "SHORT ADIDAS CLUB",
                'precio' => 35.0,
                'imagen' => "club-rosa",
                'categoria_id' => 2,
                'disponible' => true,
                'descripcion' => "Short rosa, diseñado para CrossFit, Fitness & Gym, y Activity. Para mujer.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "PANTALON NIKE YOGA CROP",
                'precio' => 21.60,
                'imagen' => "yoga-crop",
                'categoria_id' => 2,
                'disponible' => true,
                'descripcion' => "Pantalón corto de yoga en negro, ideal para Cross Training. Para mujer.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Adidas FRLFT Pro",
                'precio' => 52.5,
                'imagen' => "frlft-pro",
                'categoria_id' => 3,
                'disponible' => true,
                'descripcion' => "Camiseta para actividades intensas como CrossFit y fitness, combina tecnología avanzada y diseño ergonómico para máximo rendimiento.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok Vector",
                'precio' => 19.99,
                'imagen' => "vector",
                'categoria_id' => 3,
                'disponible' => true,
                'descripcion' => "Ideal para el gimnasio, esta camiseta combina confort con durabilidad para soportar entrenamientos intensos.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Nike Dri-Fit",
                'precio' => 35.71,
                'imagen' => "tirantes",
                'categoria_id' => 3,
                'disponible' => true,
                'descripcion' => "Camiseta de tirantes diseñada para Cross Training, utiliza tecnología Dri-Fit para mantenerte seco y cómodo.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Adidas 3S",
                'precio' => 28.0,
                'imagen' => "s3",
                'categoria_id' => 3,
                'disponible' => true,
                'descripcion' => "Diseñada para CrossFit, fitness y actividades generales, esta camiseta combina estilo clásico con funcionalidad.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Under Armour HG Racer",
                'precio' => 15.4,
                'imagen' => "hg-racer",
                'categoria_id' => 3,
                'disponible' => true,
                'descripcion' => "Camiseta de tirantes ligera y transpirable, perfecta para Cross Training, ofrece libertad de movimiento y comodidad.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Unchained Breath",
                'precio' => 49.99,
                'imagen' => "mid-rise",
                'categoria_id' => 4,
                'disponible' => true,
                'descripcion' => "Diseñadas para actividades como CrossFit y fitness, estas mallas ofrecen ajuste y comodidad, con tecnología que favorece la transpiración.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok RIE",
                'precio' => 34.99,
                'imagen' => "rie",
                'categoria_id' => 4,
                'disponible' => true,
                'descripcion' => "Mallas óptimas para el gimnasio, combinan estilo y funcionalidad con tejido que mejora la movilidad y el confort.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok Lux",
                'precio' => 54.99,
                'imagen' => "lux",
                'categoria_id' => 4,
                'disponible' => true,
                'descripcion' => "Adecuadas para fitness, con diseño premium que asegura ajuste perfecto y soporte durante ejercicios intensos.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Nike Dri-Fit",
                'precio' => 34.94,
                'imagen' => "cortas-drifit",
                'categoria_id' => 4,
                'disponible' => true,
                'descripcion' => "Cortas, ideales para Cross Training, utilizan tecnología Dri-Fit para mantener la frescura y soporte durante entrenamientos.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok Workout Ready",
                'precio' => 40.0,
                'imagen' => "ready",
                'categoria_id' => 4,
                'disponible' => true,
                'descripcion' => "Diseñadas para Cross Training, estas mallas combinan comodidad y soporte, ideales para cualquier tipo de entrenamiento.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Under Armour Rush HG Seamless",
                'precio' => 49.99,
                'imagen' => "HOODIE-LIFT-HEAVY",
                'categoria_id' => 5,
                'disponible' => true,
                'descripcion' => "Sudadera para mujer, ideal para CrossFit, combina estilo y funcionalidad con diseño cropped y color negro.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Nike Yoga Cover Up 2",
                'precio' => 38.49,
                'imagen' => "nike-yoga",
                'categoria_id' => 5,
                'disponible' => true,
                'descripcion' => "Sudadera sin capucha, diseñada específicamente para yoga, ofrece libertad de movimiento y comodidad en prácticas de movilidad.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok UBF Woven Layering Top",
                'precio' => 23.98,
                'imagen' => "reebok-ubf",
                'categoria_id' => 5,
                'disponible' => true,
                'descripcion' => "Manga 3/4, color blanco crudo, ideal para Cross Training, combina estilo y funcionalidad para entrenamientos versátiles.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Nike Dri-Fit",
                'precio' => 45.49,
                'imagen' => "sudadera-dryfit",
                'categoria_id' => 5,
                'disponible' => true,
                'descripcion' => "Negra para hombre, adecuada para CrossFit, fitness y actividades generales, con tecnología Dri-Fit para confort.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Reebok Identity Logo",
                'precio' => 52.5,
                'imagen' => "reebok-identity",
                'categoria_id' => 5,
                'disponible' => true,
                'descripcion' => "Gris para hombre, enfocada en Fitness & Gym, combina estilo clásico con funcionalidad para el ejercicio.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Adidas con Capucha",
                'precio' => 68.99,
                'imagen' => "velites",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Comba pesada, ideal para entrenamiento funcional, mejora forma física y desarrollo muscular con diseño avanzado para velocidad y fuerza.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Timecap Pack Whipper 2.0",
                'precio' => 22.46,
                'imagen' => "timecap",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Comba con mango largo para rotación mejorada, apta para todos los niveles, enfocada en mejorar la velocidad de los saltos dobles.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Picsil Azor 2 Agujeros",
                'precio' => 35.95,
                'imagen' => "picsil",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Calleras para Crosstraining, diseño único para protección y agarre, fabricadas con material transpirable y resistente.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Harbinger Hexcore - Mujer",
                'precio' => 35.9,
                'imagen' => "harbinger",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Cinturón diseñado para Cross Training, ofrece soporte lumbar óptimo con diseño específico para mujeres.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "Trainlikefight Rainbow Cookie Beast",
                'precio' => 33.96,
                'imagen' => "trainlikefight",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Cinturón para Crosstraining, asegura postura correcta en levantamiento de pesos, diseño que proporciona sujeción y protección lumbar.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' => "TrainLikeFight Loud",
                'precio' => 23.95,
                'imagen' => "callera-train",
                'categoria_id' => 6,
                'disponible' => true,
                'descripcion' => "Calleras de competición para Crosstraining, ofrecen agarre extremo y protección contra rozaduras, diseñadas para atletas exigentes.",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),    
          
        
        ];

        DB::table('productos')->insert($datos); 
    }
}
